version: '3.3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: college
    depends_on:
     - db
    volumes:
    - .:/var/www/html
    ports:
     - 8000:80
  db:
    container_name: mysql1
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
     - 6033:3306
  admin:    
    image: adminer
    ports:      
      - 8080:8080
  composer:
    restart: 'no'
    image: composer
    command: install
    volumes:
    - .:/app

      